spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC


  web:
    resources:
      add-mappings: 'false'


  mvc:
    log-resolved-exception: 'false'
    throw-exception-if-no-handler-found: 'true'

  data:
    web:
      pageable:
        one-indexed-parameters: true


  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 20



springdoc:
  api-docs:
    path: /api-docs

server:
  tomcat:
    threads:
      min-spare: 200
    mbeanregistry:
      enabled: 'true'

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    prometheus:
      enabled: 'true'

ticketing:
  queue:
    server:
      url: ${QUEUE_SERVER_URL}