spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC


  web:
    resources:
      add-mappings: 'false'


  mvc:
    log-resolved-exception: 'false'
    throw-exception-if-no-handler-found: 'true'

  data:
    web:
      pageable:
        one-indexed-parameters: true





springdoc:
  api-docs:
    path: /api-docs

server:
  tomcat:
    mbeanregistry:
      enabled: 'true'

management:
  endpoints:
    web:
      exposure:
        include: prometheus
    prometheus:
      enabled: 'true'
