management:
  endpoints:
    web:
      exposure:
        include: prometheus
    prometheus:
      enabled: 'true'

spring:
  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update

ticketing:
  jwt:
    secret: d2VhcmVuYXZ5c3dkZXZlbG9wZXJzLmFuZGlhbW1pbmp1bjMwMjE=
    expiration-hours: '24'
    issuer: minjun
