version: '3'
services:
  initdb:
    build:
      context: .
      dockerfile: ./initdb/Dockerfile
    volumes:
      - ./initdb/initdb.sh:/initdb.sh
      - ./initdb/sqls:/sqls
      - ./initdb/bastion.pem:/bastion.pem
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      BASTION_HOST: ${BASTION_HOST}
      BASTION_USERNAME: ${BASTION_USERNAME}
  
  k6:
    depends_on: 
      initdb:
        condition: service_completed_successfully
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
      - ./results:/results
    environment:
      HOST: ${HOST}
      GRAFANA_HOST: ${GRAFANA_HOST}
      K6_PROMETHEUS_RW_SERVER_URL: ${K6_PROMETHEUS_RW_SERVER_URL}
      K6_PROMETHEUS_RW_USERNAME: ${K6_PROMETHEUS_RW_USERNAME}
      K6_PROMETHEUS_RW_PASSWORD: ${K6_PROMETHEUS_RW_PASSWORD}
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: true
      OUTPUT_HTML_DIR: "/results"
    command: run /scripts/${ENTRYPOINT} -o experimental-prometheus-rw 


  