version: '3'
services:
  initdb:
    build:
      context: .
      dockerfile: ./initdb/Dockerfile
    volumes:
      - ./initdb/initdb.sh:/initdb.sh
      - ./initdb/sqls:/sqls
      - ./initdb/bastion.pem:/bastion.pem
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      BASTION_HOST: ${BASTION_HOST}
      BASTION_USERNAME: ${BASTION_USERNAME}
  
  k6:
    depends_on: 
      initdb:
        condition: service_completed_successfully
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
    environment:
      HOST: http://3.36.100.189/api
    command: run /scripts/${ENTRYPOINT}


  