version: '3'
services:
  init:
    build:
      context: .
      dockerfile: ./initdb/Dockerfile
    volumes:
      - ./initdb/initdb.sh:/initdb.sh
      - ./initdb/init.sql:/init.sql
      - ./initdb/bastion.pem:/bastion.pem
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      BASTION_HOST: ${BASTION_HOST}
      BASTION_USERNAME: ${BASTION_USERNAME}