spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USERNAME}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_SCHEMA}?serverTimezone=UTC&characterEncoding=UTF-8&useLegacyDatetimeCode=false

server:
  port: ${PORT}

ticketing:
  jwt:
    secret: ${JWT_SECRET}
    expiration-hours: ${JWT_EXPIRATION_HOURS}
    issuer: ${JWT_ISSUER}
